[build]
publish = "public"
command = "npm rebuild && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "20.17.0"

[[redirects]]
  from = "https://cobalt-docs.netlify.app/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.cobalt.io/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true

# Redirects for the old docs.cobalt.io API documentation to the new location
[[redirects]]
  from = "/v1"
  to = "/cobalt-api/documentation/v1"
  status = 301
[[redirects]]
  from = "/v2"
  to = "/cobalt-api/documentation/v2"
  status = 301
[[redirects]]
  from = "/platform-deep-dive/scans*"
  to = "/scans/:splat"
  status = 301

# Best practices redirects to external site
[[redirects]]
  from = "/bestpractices/protect-against-xxe/"
  to = "https://www.cobalt.io/blog/how-to-execute-an-xml-external-entity-injection-xxe/"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/insecure-deserialization/"
  to = "https://www.cobalt.io/blog/the-anatomy-of-deserialization-attacks"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/secure-design/"
  to = "https://www.cobalt.io/learning-center/pentester-guide-to-prevent-insecure-design-in-sql"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/api-rate-limiting/"
  to = "https://www.cobalt.io/vulnerability-wiki/v2-authentication/no-rate-limiting-on-a-form"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/prevent-ssti/"
  to = "https://www.cobalt.io/blog/a-pentesters-guide-to-server-side-template-injection-ssti"
  status = 301
  force = true
  
[[redirects]]
  from = "/bestpractices/input-validation/"
  to = "https://www.cobalt.io/vulnerability-wiki/v5-validation-sanitization"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/prevent-security-misconfig/"
  to = "https://www.cobalt.io/blog/prevent-security-misconfigurations"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/protect-against-ssrf/"
  to = "https://www.cobalt.io/learning-center/server-side-request-forgery-ssrf-overview"
  status = 301
  force = true
  
[[redirects]]
  from = "/bestpractices/*"
  to = "https://www.cobalt.io/learning-center/"
  status = 301
  force = true
