[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && git checkout f82dd5e && cd ../..   && hugo"   
  
[build.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://cobalt-docs-test.netlify.app"
  to = "https://co27.io"
  status = 301

[[redirects]]
  from = "/*"
  to = "/docs/:splat"
  status = 200
