[build]
publish = "public"
command = "npm rebuild && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.135.0"
HUGO_ENV = "production"
NODE_VERSION = "20.17.0"

[[redirects]]
  from = "https://cobalt-docs.netlify.app/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.cobalt.io/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true

# Redirects for the old docs.cobalt.io API documentation to the new location
[[redirects]]
  from = "/v1"
  to = "/cobalt-api/documentation/v1"
  status = 301
[[redirects]]
  from = "/v2"
  to = "/cobalt-api/documentation/v2"
  status = 301
