[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"   
  
[build.environment]
HUGO_VERSION = "0.105.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://cobalt-docs.netlify.app"
  to = "https://developer.cobalt.io"
  status = 301
