[build]
publish = "public"
command = "npm rebuild && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.148.2"
HUGO_ENV = "production"
NODE_VERSION = "20.17.0"

[[redirects]]
  from = "https://cobalt-docs.netlify.app/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://developer.cobalt.io/*"
  to = "https://docs.cobalt.io/:splat"
  status = 301
  force = true

# Redirects for the old docs.cobalt.io API documentation to the new location
[[redirects]]
  from = "/v1"
  to = "/cobalt-api/documentation/v1"
  status = 301
[[redirects]]
  from = "/v2"
  to = "/cobalt-api/documentation/v2"
  status = 301
[[redirects]]
  from = "/platform-deep-dive/scans*"
  to = "/scans/:splat"
  status = 301

# Best practices redirects to external site
[[redirects]]
  from = "/bestpractices/protect-against-xxe/"
  to = "https://www.cobalt.io/blog/how-to-execute-an-xml-external-entity-injection-xxe/"
  status = 301
  force = true

[[redirects]]
  from = "/bestpractices/*"
  to = "https://www.cobalt.io/learning-center/"
  status = 301
  force = true
