[build]
publish = "public"
command = "cd themes/docsy && git submodule update -f --init && git checkout f82dd5e && cd ../..   && hugo"   
  
[build.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
