#!/usr/bin/env bash
# Validates a branch name against the standardized naming scheme.
# Input (env): BRANCH_NAME
set -euo pipefail

# Regex to match the Jira ticket naming convention. See CONTRIBUTING.md for details.
# dependabot/ is added to allow dependabot created PRs
# gh-readonly-queue/main/pr-[0-9]+-[a-fA-F0-9]+ is added to allow temporary branches created by GitHub merge queues
REGEX="^revert-[0-9]+-|^dependabot/|^gh-readonly-queue/|^docs/(NO-TICKET|no-ticket|[A-Z]+[0-9]?-[0-9]+)/.+$|^(feature|fix|chore|maintenance)/[A-Z]+[0-9]?-[0-9]+/.+$"

if [[ "${BRANCH_NAME}" =~ ${REGEX} ]]; then
  exit 0
fi

cat <<EOF
========================================================================
Error: Invalid branch name: $BRANCH_NAME

Branch names must match one of the following patterns:

  feature/<TICKET>/<summary>       e.g. feature/PX-1234/add-new-feature
  fix/<TICKET>/<summary>           e.g. fix/PX-1234/ensure-bids-ac
  chore/<TICKET>/<summary>         e.g. chore/INFRA-1234/bump-deps
  maintenance/<TICKET>/<summary>   e.g. maintenance/PX-3455/update-spring
  docs/<TICKET-or-NO-TICKET>/<summary>
                                   e.g. docs/NO-TICKET/fix-typo
  revert-<N>-<anything>            (auto-generated by GitHub revert PRs)
  dependabot/<anything>            (auto-generated by Dependabot)
  gh-readonly-queue/<anything>     (auto-generated by GitHub merge queues)

<TICKET> must be the Jira key in UPPERCASE with a hyphen (e.g. PX-1234,
INFRA-234). Only docs/ may use NO-TICKET.
========================================================================
EOF

exit 1
