name: "Check the branch name"
on:
  push:
    branches-ignore:
      - 'main'
permissions:
  contents: read
jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: cobalthq/cobalt-github/.github/actions/check-branch-name@949578c037dd813e112ef8f8b85ebab60dc261fb # cobalt-github main as of 2026-05-20
